site_name: RedRunner
site_url: https://redrunnner.js.org/
site_author: Andrew Buchan
site_description: "A framework with legs"
repo_url: "https://redrunnerjs.github.com/redrunner.github.io"
copyright: "MIT license"

edit_uri: edit/dev/docs/

theme:
    name: null
    custom_dir: theme

extra_javascript:
  - static/js/index.js

extra:
  lib_url: https://github.com/andyhasit/redrunner
  favicon: /static/img/favicon.png
  theme_color: "#00818a"

markdown_extensions:
    - toc:
        #anchorlink: true
        #baselevel: 0
        toc_depth: 2-5
nav:
  - Home: /
  - Tour:
    - At a glance: /tour/at-a-glance
    - Basics: /tour/basics
    - Advanced: /tour/advanced